### ISSUE TITLE
Produces broken image

### ISSUE THREAD

**Issue by harryhuk** [scala-native/scala-native-example#16]
Hi,
I just cloned this project (to Ubuntu 16.04)
It builds fine, and runs, but the image0.ppm file is reporting its height as `22331248`

the top 2 lines of the output are:

> P3
> 800 22331248

If I edit the height to be 600, to match the scala src, I can then open the file, although the colours are very diifferent from  the png file supplied.

If I explicitly set the type of W and H to Int, it runs quicker, (42s vs 64s) and the width reported is:

> P3
> 800 18177904

again if I edit the height to be 600, I get (nearly) the same png, but still very different colours to the example supplied.

Nothing obviously wrong in the source scala. I haven't changed any of the project files, and just did:

> sbt run

**Comment by harryhuk** [comment]
It looks like a random value is being scribbled over H?

**Comment by harryhuk** [comment]
Or could be a bug in fprintf?

**Comment by Yoitsumi** [comment]
It's a bug with vararg functions introduced in scala-native/scala-native#299, i'm already working on a fix for that

**Comment by harryhuk** [comment]
Excellent, thanks!

**Comment by densh** [comment]
Fixed in https://github.com/scala-native/scala-native/pull/322

**Comment by harryhuk** [comment]
Cheers!
