### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native-example#4]
This repo badly needs some continuous integration.

**Comment by frgomes** [comment]
It can now be done easily with dependencies in public repositories.


Richard Gomes http://rgomes.info/ http://linkedin.com/in/rgomes UK: +44(77)9955-6813

via CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.4.40&pv=5.1&source=email_footer_2] On Sat, Jul 02, 2016 at 2:29 PM, Denys Shabalin < notifications@github.com [notifications@github.com] > wrote:
This repo badly needs some continuous integration.

**Comment by densh** [comment]
It should be possible now, given that we publish snapshots of the main repo publicly.

**Comment by frgomes** [comment]
We are not ready for it yet. Please see #7

**Comment by frgomes** [comment]
I've added the Travis config file but it does not seen to be automagically kicking off the build. I will review this later.

**Comment by densh** [comment]
You also need to enable it on travis website.

**Comment by frgomes** [comment]
I will try a dual build on osx and debian and review the documentation later.
